<html>
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=0.6">
	    <link href="css/bootstrap.min.css" rel="stylesheet">
	    <link rel="stylesheet" type="text/css" href="css/custom.css">
	    <link rel="stylesheet" type="text/css" href="css/print.css">
	</head>
	<body>
		<script>
		$(document).ready(function() { 
			var $url = parent.document.location;
			document.url = $url;
		});

		</script>
		<!--<page size="A4" style="margin-left:0;margin-right:0;">-->
		<div id="invoice-wrapper">
			<div class="row">
				<div id="invoice-header">
					<div id="invoice-header-logo-div">
						<img id="invoice-header-logo" src="img/logo.png"/>
						<h2 id="invoice-header-logo-text">YourLogo Inc.</h2>
					</div>
					<div id="invoice-header-info">
						<div id="invoice-header-info-place">
							<span class="glyphicon glyphicon-pushpin" id="invoice-header-info-icon"></span>
							<p class="invoice-header-info-place-text">NewYork, Adress: 350 Fifth Avenue, 34th floor. NewYork, NY 10118-3299 USA</p>
						</div>
						<div id="invoice-header-info-tel">
							<span class="glyphicon glyphicon-earphone" id="invoice-header-info-icon"></span>
							<p class="invoice-header-info-place-text">Tel: +1-212-290-4700. Fax: +1-212-736-1300</p>
						</div>
						<div id="invoice-header-info-web">
							<span class="glyphicon glyphicon-globe" id="invoice-header-info-icon"></span>
							<p class="invoice-header-info-place-text">www.yourlogo.com</p>
						</div>
					</div>
				</div>		
			</div>
			<div class="row">
				<div id="invoice-data">
					<div id="invoice-data-to">
						<h3>FATTURA <span>per:</span></h3>
					</div>
					<div id="invoice-data-invoice-text">
						<h1><strong>FATTURA</strong></h1>
					</div>
					<div><hr id="invoice-data-line"></div>
					<div id="invoice-data-to-company">
						<h5>
							<strong>Andi Hartono</strong>
						</h5>
					</div>
					<div id="invoice-data-to-adress">
						<h5>
							Simple Street No: 12/5 Genoa 15888, ITALY P: 0080 878 87 8 M: info@domainame.com
						</h5>
					</div>
					<div id="invoice-data-datas">
						<div id="invoice-data-number">
							<h5>
								<strong id="invoice-data-number-item-1">FATTURA NUM</strong><span id="invoice-data-separator"></span> <span id="invoice-data-item">12555589</span>
							</h5>
						</div>
						<div id="invoice-data-date">
							<h5>
								<strong id="invoice-data-number-item-2">DATA FATTURA</strong><span id="invoice-data-separator"></span> <span id="invoice-data-item">29/07/2015 </span>
							</h5>
						</div>
						<div id="invoice-data-account">
							<h5>
								<strong id="invoice-data-number-item-3">CLIENTE NUM</strong><span id="invoice-data-separator"></span> <span id="invoice-data-item">0005489 </span>
							</h5>
						</div>
						<div id="invoice-data-amount">
							<div id="invoice-data-amount-bg">
								<h5>TOTALE FATTURA </h5> <strong id="invoice-data-amount-value">€3,232.15</strong>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div id="invoice-item">
					<div id="invoice-item-id" class="col-sm-1">
						<h5>ID</h5>
					</div>
					<div id="invoice-item-description" class="col-sm-3">
						<h5>DESCRIZONE</h5>
					</div>
					<div id="invoice-item-price" class="col-sm-2">
						<h5>PREZZO</h5>
					</div>
					<div id="invoice-item-total" class="col-sm-3">
						<h5>TOTALE</h5>
					</div>
					<hr id="invoice-item-line">
					
				</div>
				<div id="invoice-item-placeholder">
						<!-- PLACEHOLDER -->
				</div>
				<div id="invoice-item-placeholder-total">
						<!-- PLACEHOLDER -->
				</div>
				<div id="invoice-item-placeholder-total-final">
						<p><strong>TOTAL</strong></p><!-- PLACEHOLDER -->
				</div>
				<div id="invoice-item-terms">
					<h5><strong>TERMINI / CONDIZIONI</strong></h5>
					<h6>The folowing invoice is a template generated by myWORK, this is not intended as final version of the invoice of our system.</h6>
					<h6><strong>Thanks for business</strong></h6>
				</div>
			</div>	
			<div class="row">
				<div id="invoice-payment">
					<div id="invoice-payment-data">
						<h5><strong>PAGAMENTO</strong></h5>
						<h6>Ahmad</h6>
						<h6>bank of south africa</h6>
						<h6><strong>IBAN:</strong> IT0943208175647382938476</h6>
					</div>
					<div id="invoice-payment-accepted">
						<h5><strong>PAGAMENTI ACCETTATI</strong></h5>
						<h6>Visa, PayPal, MasterCard, Bonifico Bancario</h6>
					</div>
					<div id="invoice-payment-signature">
						<h3>Company Manager</h3>
						<img src="img/sign.png">
						<h4><strong>Barack Obama</strong></h4>
					</div>
				</div>
			</div>
			<div class="row">
				<div id="invoice-footer">
					<hr id="invoice-footer-line">
					<div id="invoice-footer-disclaimer">
					<br>
						<h6>Lorem ipsum sir dolor sit aime, Cantami o diva del pelide achille l'ira funesta che infinita addunse, morte agli Achei</h6>
					</div>
				</div>
			</div>
		</div>
		</page>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
	</body>
</html>